INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add free course', 7, 'add_freecourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change free course', 7, 'change_freecourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete free course', 7, 'delete_freecourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view free course', 7, 'view_freecourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add practical course', 8, 'add_practicalcourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change practical course', 8, 'change_practicalcourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete practical course', 8, 'delete_practicalcourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view practical course', 8, 'view_practicalcourse');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add course detail', 9, 'add_coursedetail');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change course detail', 9, 'change_coursedetail');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete course detail', 9, 'delete_coursedetail');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view course detail', 9, 'view_coursedetail');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add course chapter', 10, 'add_coursechapter');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change course chapter', 10, 'change_coursechapter');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete course chapter', 10, 'delete_coursechapter');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view course chapter', 10, 'view_coursechapter');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add 课程分类表', 11, 'add_category');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change 课程分类表', 11, 'change_category');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete 课程分类表', 11, 'delete_category');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view 课程分类表', 11, 'view_category');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add course section', 12, 'add_coursesection');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change course section', 12, 'change_coursesection');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete course section', 12, 'delete_coursesection');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view course section', 12, 'view_coursesection');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add teacher', 13, 'add_teacher');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change teacher', 13, 'change_teacher');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete teacher', 13, 'delete_teacher');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view teacher', 13, 'view_teacher');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add go learn', 14, 'add_golearn');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change go learn', 14, 'change_golearn');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete go learn', 14, 'delete_golearn');
INSERT INTO luffycity.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view go learn', 14, 'view_golearn');