# Generated by Django 3.0.3 on 2020-05-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课程的分类')),
                ('categoryType', models.SmallIntegerField(choices=[(0, '免费课'), (1, '实战课')])),
            ],
            options={
                'verbose_name': '课程分类表',
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.SmallIntegerField(verbose_name='第几章')),
                ('title', models.CharField(max_length=32, verbose_name='课程章节名称')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatGoingLearn', models.TextField(verbose_name='我将学到哪些内容')),
                ('brief', models.CharField(max_length=1024, verbose_name='课程简介')),
                ('qqGroup', models.CharField(blank=True, max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='讲师名字')),
                ('brief', models.TextField(max_length=1024, verbose_name='讲师介绍')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='课程的名称')),
                ('courseImage', models.ImageField(upload_to='course/%Y-%m', verbose_name='课程的图片')),
                ('studyNumber', models.IntegerField(verbose_name='学习人数')),
                ('hours', models.IntegerField(verbose_name='时长')),
                ('course_slogan', models.CharField(default='课程', max_length=1024, verbose_name='课程概述')),
                ('level', models.SmallIntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=1)),
                ('courseType', models.SmallIntegerField(choices=[(0, '免费课'), (1, '实战课'), (2, '轻课'), (3, '就业班')])),
                ('price', models.IntegerField(default=99, verbose_name='价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.Category', verbose_name='课程的分类')),
                ('course', models.ManyToManyField(to='Course.CourseChapter')),
                ('courseDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='课程的名称')),
                ('courseImage', models.ImageField(upload_to='course/%Y-%m', verbose_name='课程的图片')),
                ('studyNumber', models.IntegerField(verbose_name='学习人数')),
                ('hours', models.IntegerField(verbose_name='时长')),
                ('course_slogan', models.CharField(default='课程', max_length=1024, verbose_name='课程概述')),
                ('level', models.SmallIntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=1)),
                ('courseType', models.SmallIntegerField(choices=[(0, '免费课'), (1, '实战课'), (2, '轻课'), (3, '就业班')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.Category', verbose_name='课程的分类')),
                ('course', models.ManyToManyField(to='Course.CourseChapter')),
                ('courseDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课时名称')),
                ('freeTrail', models.BooleanField(default=False, help_text='是否可试看')),
                ('sectionType', models.SmallIntegerField(choices=[(0, '文档'), (1, '练习'), (2, '视频')], default=2)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseChapter')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='teachers',
            field=models.ManyToManyField(to='Course.Teacher', verbose_name='课程讲师'),
        ),
    ]
