# Generated by Django 3.0.3 on 2020-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=128, verbose_name='课程的名称'),
        ),
    ]
