# Generated by Django 3.0.3 on 2020-05-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='freecourse',
            old_name='course',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='practicalcourse',
            old_name='course',
            new_name='chapter',
        ),
    ]
