# Generated by Django 3.0.3 on 2020-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20200508_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecourse',
            name='course_slogan',
        ),
        migrations.RemoveField(
            model_name='practicalcourse',
            name='course_slogan',
        ),
        migrations.AddField(
            model_name='freecourse',
            name='slogan',
            field=models.CharField(default=1, max_length=1024, verbose_name='课程概述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicalcourse',
            name='slogan',
            field=models.CharField(default='1', max_length=1024, verbose_name='课程概述'),
            preserve_default=False,
        ),
    ]
