# Generated by Django 3.0.3 on 2020-05-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20200508_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='whatGoingLearn',
        ),
        migrations.CreateModel(
            name='GoLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='将会学到的内容')),
                ('courseDetail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Course.CourseDetail')),
            ],
        ),
    ]
