# Generated by Django 3.0.3 on 2020-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20200508_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='brief',
            field=models.TextField(verbose_name='课程简介'),
        ),
    ]
