# Generated by Django 3.0.3 on 2020-05-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20200508_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='number',
            field=models.IntegerField(default=0, verbose_name='课程小节'),
        ),
    ]
