# Generated by Django 3.0.3 on 2020-05-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_coursedetail_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalcourse',
            name='isBuy',
            field=models.BooleanField(default=False),
        ),
    ]
