# Generated by Django 3.0.3 on 2020-05-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_practicalcourse_isbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='课程的名称')),
                ('courseImage', models.ImageField(upload_to='course/%Y-%m', verbose_name='课程的图片')),
                ('studyNumber', models.IntegerField(verbose_name='学习人数')),
                ('hours', models.IntegerField(verbose_name='时长')),
                ('slogan', models.CharField(max_length=1024, verbose_name='课程概述')),
                ('courseType', models.SmallIntegerField(choices=[(0, '免费课'), (1, '实战课'), (2, '轻课'), (3, '就业班')])),
                ('price', models.IntegerField(default=99, verbose_name='价格')),
                ('salary', models.CharField(max_length=128, verbose_name='就业薪资')),
                ('employmentRate', models.FloatField(verbose_name='就业率')),
                ('courseDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course.CourseDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='practicalcourse',
            name='isBuy',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='模块')),
                ('chapter', models.ManyToManyField(to='Course.CourseChapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.EmploymentCourse')),
            ],
        ),
    ]
