# Generated by Django 3.0.3 on 2020-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_auto_20200510_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module',
            field=models.SmallIntegerField(default=0, verbose_name='第几模块'),
            preserve_default=False,
        ),
    ]
