# Generated by Django 3.0.3 on 2020-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_module_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='homeworkContent',
            field=models.TextField(blank=True, null=True, verbose_name='作业内容'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='homeworkTitle',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='作业题目'),
        ),
    ]
