# Generated by Django 3.0.3 on 2020-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_auto_20200515_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='homeworkPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='奖学金'),
        ),
    ]
