# Generated by Django 3.0.3 on 2020-05-14 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_module_module'),
        ('Account', '0002_auto_20200514_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='courses',
            field=models.ManyToManyField(related_name='userCourse', to='Course.EmploymentCourse'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=32, verbose_name='学生手机号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='老师信息')),
            ],
        ),
    ]
