# Generated by Django 3.0.3 on 2020-05-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_module_module'),
        ('Account', '0004_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='completeSection',
        ),
        migrations.RemoveField(
            model_name='account',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='account',
            name='identity',
        ),
        migrations.AddField(
            model_name='student',
            name='completeSection',
            field=models.ManyToManyField(to='Course.CourseSection'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='userCourse', to='Course.EmploymentCourse'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(max_length=32, verbose_name='老师手机号'),
        ),
    ]
