# Generated by Django 3.0.3 on 2020-05-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_account_identity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
