# Generated by Django 3.0.3 on 2020-05-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classList',
        ),
        migrations.RemoveField(
            model_name='student',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.AlterField(
            model_name='student',
            name='QQ',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学生QQ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studentTeacher', to='Account.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学生手机号'),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
