# Generated by Django 3.0.3 on 2020-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='environment',
            field=models.CharField(max_length=255, verbose_name='环境'),
        ),
    ]
