# Generated by Django 3.0.3 on 2020-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0002_auto_20200514_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='situation',
            field=models.IntegerField(choices=[(1, '一般'), (2, '紧急'), (3, '十万火急')], default=1, verbose_name='情况'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.IntegerField(choices=[(1, '未处理'), (2, '已回复')], default=1, verbose_name='进度'),
        ),
    ]
