# Generated by Django 3.0.3 on 2020-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0003_auto_20200514_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='situation',
            field=models.IntegerField(choices=[(0, '一般'), (1, '紧急'), (2, '十万火急')], default=1, verbose_name='情况'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '已回复')], default=1, verbose_name='进度'),
        ),
    ]
