# Generated by Django 3.0.3 on 2020-05-15 10:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Classroom', '0005_auto_20200514_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.CharField(max_length=64, verbose_name='模块章节')),
                ('title', models.CharField(max_length=32, verbose_name='题目')),
                ('file', models.FileField(upload_to='media/task/', verbose_name='作业内容')),
                ('content', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('achievement', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='成绩')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='老师点评')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Account.Teacher', verbose_name='批改老师')),
            ],
        ),
    ]
