# Generated by Django 3.0.3 on 2020-05-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_auto_20200515_2208'),
        ('Account', '0008_delete_task'),
        ('Classroom', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Course.CourseChapter', verbose_name='章节'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Account.Teacher', verbose_name='导师'),
            preserve_default=False,
        ),
    ]
