# Generated by Django 3.0.3 on 2020-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0007_auto_20200515_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solve',
            field=models.TextField(blank=True, null=True, verbose_name='解决内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '已回复')], default=0, verbose_name='进度'),
        ),
    ]
