# Generated by Django 3.0.3 on 2020-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0008_auto_20200517_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(0, '未批改'), (1, '已批改')], default=0, verbose_name='进度'),
        ),
    ]
