# Generated by Django 2.2.5 on 2020-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='权限图标'),
        ),
        migrations.AlterField(
            model_name='rbacuserinfo',
            name='roles',
            field=models.ManyToManyField(blank=True, to='RBAC.Role', verbose_name='职位'),
        ),
    ]
