# Generated by Django 2.2.5 on 2020-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0002_auto_20200405_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='alias',
        ),
        migrations.AddField(
            model_name='permission',
            name='title',
            field=models.CharField(default=1, max_length=32, verbose_name='权限名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='权限URL别名'),
        ),
    ]
