# Generated by Django 2.2.5 on 2020-04-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0003_auto_20200405_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacuserinfo',
            name='password',
            field=models.CharField(default=123456, max_length=150, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
