# Generated by Django 2.2.5 on 2020-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0004_rbacuserinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='duty',
            field=models.CharField(default='Leaders knock code', max_length=256, verbose_name='职责'),
            preserve_default=False,
        ),
    ]
