# Generated by Django 2.2.5 on 2020-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, '无人敢接'), (2, '已被接取')], default=1, verbose_name='状态'),
        ),
    ]
