# Generated by Django 2.2.5 on 2020-04-06 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(default=123, upload_to='', verbose_name='作业内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
    ]
