# Generated by Django 2.2.5 on 2020-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200406_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='task/', verbose_name='作业内容'),
        ),
    ]
