# Generated by Django 2.2.5 on 2020-04-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200406_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RBAC.RbacUserInfo', verbose_name='批改老师'),
        ),
    ]
