# Generated by Django 2.2.5 on 2020-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200406_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='media/task/', verbose_name='作业内容'),
        ),
    ]
